---
apiVersion: v1
data:
  .dockerconfigjson: ewogICJjcmVkSGVscGVycyI6IHsKICAgICJnY3IuaW8iOiAiZ2Nsb3VkIiwKICAgICJ1cy5nY3IuaW8iOiAiZ2Nsb3VkIiwKICAgICJldS5nY3IuaW8iOiAiZ2Nsb3VkIiwKICAgICJhc2lhLmdjci5pbyI6ICJnY2xvdWQiLAogICAgInN0YWdpbmctazhzLmdjci5pbyI6ICJnY2xvdWQiLAogICAgIm1hcmtldHBsYWNlLmdjci5pbyI6ICJnY2xvdWQiCiAgfQp9
kind: Secret
metadata:
  creationTimestamp: null
  name: resistry-gcr
  namespace: app
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Namespace
metadata:
  name: app

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-v1
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-v1
  template:
    metadata:
      labels:
        app: app-v1
    spec:
      containers:
      - name: pozos-website
        image: php:apache
        ports:
        - name: pozos-website
          containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: pozos-website
        env:
        - name: USERNAME
          value: "toto"
        - name: PASSWORD
          value: "python"
      
      initContainers:      
      - name: pozos-api
        image: eu.gcr.io/traefikproject/student-list:latest
        imagePullPolicy: Always
        ports:
        - name: pozos-api
          containerPort: 5000
        volumeMounts:
        - mountPath: /data #/student_age.json
          name: studentjson      
      
      volumes:
      - name: pozos-website
        hostPath:
          # directory location on host
          path: /home/barry2abdulrahim/gitOps-student-list/website
          # this field is optional
          type: Directory 
          
      - name: studentjson
        hostPath:
          # directory location on host
          path: /home/barry2abdulrahim/gitOps-student-list/simple_api
          # this field is optional
          type: Directory
         
      imagePullSecrets:
      - name: resistry-gcr

---
apiVersion: v1
kind: Service
metadata:
  name: app-v1
  namespace: app
  labels:
    app: app-v1
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: app-v1
  selector:
    app: app-v1

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: app-tls
  namespace: app
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`studentlist.demo.telemaque.fr`)
      services:
        - name: app-v1
          port: 80
  tls:
    certResolver: myresolver
